name: shoppe
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.2

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  # State management
  flutter_riverpod: ^3.0.0
  riverpod_annotation: ^3.0.0
  # A code generator for immutable classes
  freezed_annotation: ^3.1.0
  # A code generator for JSON serialization
  json_annotation: ^4.9.0
  # Prints beautiful logs
  logger: ^2.5.0
  # Flutter plugin for reading and writing simple key-value pairs for cache
  shared_preferences: ^2.5.3
  # For caching secured data
  flutter_secure_storage: ^9.2.4
  # A flutter plugin for adapting screen and font size.Guaranteed to look good on different models
  flutter_screenutil: ^5.9.3
  # Provides Awesome UI components for Flutter
  shadcn_ui: ^0.31.2
  # Networking
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  # For routing
  auto_route: ^10.1.2
  # Caches images
  cached_network_image: ^3.4.1
  # Provides a simple way to validate OTP
  pinput: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
   # A build system for Dart code generation and modular compilation.
  build_runner: ^2.4.14
  # code generator for riverpod
  riverpod_generator: ^3.0.0
  # Custom Lint rules are a powerful way to improve the maintainability of a project
  custom_lint: ^0.8.0
  # A developer tool for users of Riverpod, designed to help stop common issues and simplify repetitive tasks.
  riverpod_lint: ^3.0.0
  # A code generator for immutable classes
  freezed: ^3.2.3
  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.9.0
  # Code generator for Retrofit
  retrofit_generator: ^10.0.0
  # Generates a native splash screen for Flutter
  flutter_native_splash: ^2.4.6
  # Changes the name of the app
  rename_app: ^1.6.5
  # Auto-route generator
  auto_route_generator: ^10.2.4

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/svgs/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/Raleway/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Raleway/Raleway-Bold.ttf
          weight: 700


flutter_assets:
  assets_path: assets/
  output_path: lib/src/core/utils/
  filename: assets.dart
  field_prefix: null